#!/usr/bin/env bash


#Take snapshots from AWS ec2 instances.

#Variables
REGION="us-east-1"
AWS=`which aws`
DESC_EC2="ec2 describe-instances"
DESC_AS="autoscaling describe-auto-scaling-instances"
DESC_VOLUME="ec2 describe-volumes"
DESC_SNAPS="ec2 describe-snapshots"
TAKESNAP="ec2 create-snapshot"
SNAP_DEL="ec2 delete-snapshot"
ALLEC2="/tmp/ec2file.txt"
ONLYEC2="/tmp/onlyec2.txt"

#Exclude autoscaling and elastic beanstalk instances.
exclude_autoscaling() {
	$AWS $DESC_EC2 --region $REGION	| jq .Reservations[].Instances[].InstanceId > $ALLEC2
	$AWS $DESC_AS --region $REGION | jq .AutoScalingInstances[].InstanceId >> $ALLEC2
	sort $ALLEC2 | uniq -u  | tr -d \" >> $ONLYEC2
}

#Generate the volume-id using the 'for' variable "instancia" from snapeia function.
lista_volumes() {
	$AWS $DESC_EC2 --region=$REGION --instance-id $1 | jq .Reservations[].Instances[].BlockDeviceMappings[].Ebs.VolumeId | tr -d \"
}

#Take snapshots from each volume with volume description, like instance, device attachment and creation date.
snapeia() {
    for instancia in `cat $ONLYEC2`; do
		  for volume in `lista_volumes $instancia`; do
			  EC2NAME=`$AWS $DESC_EC2 --region=$REGION --instance-id $instancia | jq '.Reservations[].Instances[].Tags[] | select(.["Key"] == "Name") | .Value' | tr -d \"`
       	DATE=`date '+%F -- %R'`
       	VOLDESC=`$AWS $DESC_VOLUME --region=$REGION --volume-id $volume | jq .Volumes[].Attachments[] | jq '.Device,.VolumeId,.InstanceId'| tr -d \" | tr '\n' ' '`
       	$AWS $TAKESNAP --volume-id $volume --description "snap_from_aws_utils $EC2NAME -- $VOLDESC -- $DATE" --region=$REGION
		  done
    done
}

#Delete snapshots older than 7 days.
only_seven_days() {
	SEVEN_DAYS_AGO=`date --date="7 days ago" +%F`
	for snapshot in `$AWS $DESC_SNAPS --filter "Name=description,Values=*snap_from_aws_utils*" | jq '.Snapshots[].SnapshotId' | tr -d \"`; do
		SNAP_DATE=`$AWS $DESC_SNAPS --snapshot-ids $snapshot | jq .Snapshots[].StartTime | cut -b 2-11`
			if [ "`date --date \"$SNAP_DATE\" +%s`" -lt "`date --date \"$SEVEN_DAYS_AGO\" +%s`" ]; then
				$AWS $SNAP_DEL --snapshot-id $snapshot
			fi
	done

}

#Remove temp files.
limpa_arquivos() {
	rm -rf $ALLEC2 $ONLYEC2
}

exclude_autoscaling
snapeia
limpa_arquivos
only_seven_days
